Added ability to cancel infiniteDash with attack
Juskelis/Champloo pull request #175
Opened 2017-07-13 03:36 UTC by JXVD

2017-07-13 03:59 UTC, Juskelis requested changes

2017-07-13 03:59 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +        if (specialTimeLeft < (specialTime * attackBufferWindow) && player.InputPlayer.GetButtonDown("Attack"))
This shouldn't be listening to the Inputs

2017-07-13 03:59 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +            if (attackAllowed)
This probably shouldn't be happening like this. AttackAllowed isn't supposed to be treated like transition logic internally.

2017-07-13 23:42 UTC, JXVD commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +            if (attackAllowed)
would you just want earlyAttackInput put back in as a variable?

2017-07-13 23:43 UTC, JXVD commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +        if (specialTimeLeft < (specialTime * attackBufferWindow) && player.InputPlayer.GetButtonDown("Attack"))
why? It needs to check for an attack input at some point and having a nested if statement felt unnecessary.

2017-07-14 03:13 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +        if (specialTimeLeft < (specialTime * attackBufferWindow) && player.InputPlayer.GetButtonDown("Attack"))
The logic for checking input already happens within Player. The design intention for AttackAllowed was to have it behave independent of user input.

2017-07-14 03:15 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +            if (attackAllowed)
That would be better; but I'm not sure we event need this logic anymore. From what I've seen, the Player's attack logic doesn't short circuit on state anymore.

2017-07-15 11:42 UTC, JXVD commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +            if (attackAllowed)
My understanding was that we needed to put the player into the InAttack movement state as Player.cs doesn't do that.

2017-08-08 16:16 UTC, Juskelis requested changes

2017-08-08 16:16 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
> +    private bool attackButtonHit;
Why do you have this? You're not using it anywhere.

2017-08-08 16:16 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnInfiniteDash.cs
>              if (player.InputPlayer.GetButtonDown("Attack"))
Get rid of this if statement, you don't need it

2017-08-10 02:52 UTC, Juskelis approved these changes

2017-08-10 03:30 UTC, Juskelis approved these changes

2017-08-11 05:48 UTC, Juskelis approved these changes

2017-08-11 05:48 UTC, merged