Slide
Juskelis/Champloo pull request #90
Opened 2017-05-02 03:08 UTC by JXVD

2017-05-02 05:49 UTC, Juskelis requested changes

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private Vector2 test;
This probably shouldn't be here; it's poorly named and is never actually used

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        if (GetSimulatedState() == GetComponent<OnWall>())
You should store the result of GetSimulatedState in a local variable, and GetComponent is expensive, you should do a type check here instead

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +            //decrease in speed going up, increase going down
This'll cause the player to not be able to slide far up a wall, right? How is that going to affect the air combat?

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +            goingRight = controller.collisions.Left;
Why are we making this assignment here? It isn't used in the rest of the function.

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private bool goingRight;
I'm not sure why you have this as a class level variable; both instances when you use it end up resetting it each call

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        else if (GetSimulatedState() == GetComponent<OnGround>())
Same as above

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +            if (controller.collisions.Right && velocity.x > 0)
You might want to clean up these if statements; it seems like theres a lot of redundancy here.

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +                //add in any potential -y velocity if there is any, otherwise just decay the speed
nit: comment is misleading, this branch isn't changing velocity.y at all

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        else if(GetSimulatedState() == GetComponent<InAir>() || (GetSimulatedState() == GetComponent<OnWall>() && controller.collisions.Above))
same comment as above

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        if(GetSimulatedState() == GetComponent<InAir>())
do a typecheck instead of getcomponent

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        if (GetSimulatedState() == GetComponent<InAir>())
typecheck

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        if (GetSimulatedState() == GetComponent<OnWall>())
same comments as above

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        player.ApplyForce(appliedForce);
I can see this being really dangerous down the road. I'd keep a class variable to track which way you want to move, and then do velocity updating within ApplyFriction. Take a look at OnDash, we do this same sort of idea in there.

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private PlayRandomSource wallSlideSound;
This isn't used anywhere in here

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private Vector2 groundSlideForce;
The y component of this isn't used

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private bool goingUp;
Same as goingRight

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private bool isOnWall;
This is assigned but never used

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private Vector3 appliedForce;
If you follow my other comments, this should probably be renamed. If not, this shouldn't be a class level variable

2017-05-02 05:49 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +    private float wallSlideDownDecay;
nit: decay is a misleading name for this, since it actually makes the player's speed increase

2017-05-02 21:10 UTC, JXVD commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        player.ApplyForce(appliedForce);
Doing all the force application in ApplyFriction is problematic as that method isn't tied to timing and is meant for general frame by frame changes. I would prefer to apply forces in OnStart so we don't have to get around our timing restrictions with checks in ApplyFriction

2017-05-02 21:16 UTC, JXVD commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +            //decrease in speed going up, increase going down
I envision the decay as small, but I want it to be there if we feel slide is too good. I'll also probably eventually add in the ability to jump out of slides in some capacity later on once we know how it feels.

2017-05-04 04:58 UTC, Juskelis requested changes
This is looking a lot better! sorry to rail on it so much

2017-05-04 04:58 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        else if(simulatedState is InAir)
nit: This can be pulled into the above if statement, and you can return simulatedState above rather than calling GetSimulatedState again

2017-05-04 04:58 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        else if (GetSimulatedState() == GetComponent<OnGround>())
+1

2017-05-04 04:58 UTC, Juskelis commented on Unity/Champloo/Assets/Scripts/Player/Movement States/Movement Specials/OnSlide.cs
> +        if (GetSimulatedState() == GetComponent<OnWall>())
Missed this one

2017-05-05 01:37 UTC, Juskelis approved these changes

2017-05-05 01:37 UTC, merged